apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4xMjM=
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2026-01-01T06:01:47Z"
  name: mongo-secret
  namespace: mern-ns
  resourceVersion: "129019"
  uid: 7d5ffb5f-89cd-426d-8aa6-96224739c968
type: Opaque