apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: mern-ns
spec:
  selector:
    matchLabels:
      app: mongo-app
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-container
        image: mongo:8.0.3
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongo-secret
        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: hostpath

