apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.label}}
  ports:
  - port: {{.Values.containerPort}}
    targetPort: {{.Values.containerPort}}


